language: php
php:
- 5.6
before_script:
- composer install --no-interaction --prefer-source
- npm install -g mockserver
before_deploy:
- make package
deploy:
  provider: releases
  api_key:
    secure: khKmVWXj2JWm8IJGqW57ZV8QdQVr4VgW3cZZM3+c8io9jo5h3ybeUfg9Ax1bl8GlFmpwfzBsDrMV0+/kbap04F49J7xC6yqomT1SLaIMG1ki5UE8hHVqUCT3nMEu25ld7erWD3q/y2VPeZ/3ZP908lXbooH5ziC8XR6cT8+yUIZQGJUSPWASSxVdfF0cz1Fp+ME/aALntZvIh9upE80iYX96HKoygbr0aR0rgSqoGp8Fzf9ITs52H4WcVXMo4LiRZVB8w4JPfHMDITAsuFNGTqib80itPBuxhjLqHnNb2c5+M716oogQjCCuUK0kefLRwGFQlg294ZKLxEY1j9jl+EaSHXLsvo6+VnRlE10p1nBnIN0Ff5KKaWf1r4fJWnAOOU/WOfu8MAHMdNwnLJtMZcx30o0d8nRjQy4sFIgNAmx4/U7a470V37AqH+0PQ5P81yvipaQz07uNzl9AQGcSVdwTa5qwGdjvziv/l/fDNVCdmvN7q1nsNEjsperNDkhxeoaYWwpAlPsuN0I5HCXiR5+IzpdvcKjX8TC2vOSeqw3zjW6z1Ht0RiVl4B68/ku26LfCMZ8Rie7yXfFOKtR2//8pDmZmqt/gheRHnhV7GouIDWqYM8gqYR4sd2tFrF9w1leUaisKL8mvJI7ikcRQu/DtEMeOLp8dR4Tl6RciKnE=
  file:
    - build/artifacts/tppmyone4all-php.phar
    - build/artifacts/tppmyone4all-php.zip
  on:
    repo: jilenloa/tppmyone4all-php
