language: php

php:
- 5.6

before_script:
- composer install --no-interaction --prefer-source --dev
- npm install -g mockserver

before_deploy:
- make package

deploy:
  provider: releases
  skip_cleanup: true
  api_key: "2fbda3196675f4c290a0cbe1f48b74774b7767f2"
  file:
    - build/artifacts/tppmyone4all-php.phar
    - build/artifacts/tppmyone4all-php.zip
  on:
    repo: jilenloa/tppmyone4all-php
    tags: true
