name: CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      version: '1.0.3'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 5.6

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-source

      - name: Install npm packages
        run: npm install -g mockserver

      - name: Build package
        run: make package

      - name: Deploy
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"
          gh release create v${{ needs.build.outputs.version }} \
            build/artifacts/tppmyone4all-php.phar \
            build/artifacts/tppmyone4all-php.zip \
            --title "Release v${{ needs.build.outputs.version }}" \
            --notes "Release notes for v${{ needs.build.outputs.version }}"
